# @generated by tools/gen_wire_models.py from vendor/monty-contracts/wire_bundle.json -- DO NOT EDIT.
from __future__ import annotations

from datetime import datetime
from typing import Any, ClassVar, Final, Literal

from pydantic import ConfigDict, Field, model_validator

_MISSING = object()
WIRE_BUNDLE_FORMAT: Final = 1
WIRE_BUNDLE_SHA256: Final = '989f7c2935b3ad12370d0bc52ed57f4c7604e235b34d3a46d4932d654597dab5'
WIRE_CONTRACT_VERSION: Final = 12


class StreamEventFields:
    model_config = ConfigDict(extra='forbid')
    _wire_non_null_optional: ClassVar[frozenset[str]] = frozenset(('job_id', 'session_id', 'corr_id', 'step', 'op', 'phase', 'outcome', 'optional', 'steps', 'skipped', 'error', 'error_type', 'timings', 'timeline', 'capacity', 'ts'))

    @model_validator(mode="before")
    @classmethod
    def _wire_optional_fields_are_absent_not_null(cls, value: Any) -> Any:
        if isinstance(value, dict):
            nulls = sorted(key for key in cls._wire_non_null_optional if value.get(key, _MISSING) is None)
            if nulls:
                raise ValueError(f"optional wire fields must be omitted, not null: {nulls}")
        return value

    stage: str = Field(min_length=1)
    status: Literal['done', 'ok', 'step', 'error']
    job_id: str | None = Field(default=None, min_length=1)
    session_id: str | None = Field(default=None, min_length=1)
    corr_id: str | None = Field(default=None, min_length=1)
    step: str | None = Field(default=None, min_length=1)
    op: str | None = Field(default=None, min_length=1)
    phase: str | None = Field(default=None, min_length=1)
    outcome: Literal['ok', 'error'] | None = None
    optional: bool | None = None
    steps: list[str] | None = None
    skipped: list[str] | None = None
    outputs: Any | None = None
    error: str | None = None
    error_type: str | None = Field(default=None, min_length=1)
    timings: dict[str, Any] | None = None
    timeline: dict[str, Any] | None = None
    capacity: dict[str, Any] | None = None
    ts: datetime | None = None


class StreamResultFields:
    model_config = ConfigDict(extra='allow')
    _wire_non_null_optional: ClassVar[frozenset[str]] = frozenset(('kind', 'stage', 'result_key', 'timing', 'timings', 'error', 'timeline'))

    @model_validator(mode="before")
    @classmethod
    def _wire_optional_fields_are_absent_not_null(cls, value: Any) -> Any:
        if isinstance(value, dict):
            nulls = sorted(key for key in cls._wire_non_null_optional if value.get(key, _MISSING) is None)
            if nulls:
                raise ValueError(f"optional wire fields must be omitted, not null: {nulls}")
        return value

    job_id: str = Field(min_length=1)
    session_id: str = Field(min_length=1)
    corr_id: str = Field(min_length=1)
    status: Literal['ok', 'error']
    kind: str | None = Field(default=None, min_length=1)
    stage: str | None = Field(default=None, min_length=1)
    result_key: str | None = Field(default=None, min_length=1)
    timing: dict[str, Any] | None = None
    timings: dict[str, Any] | None = None
    error: str | None = None
    timeline: dict[str, Any] | None = None


class StreamEventFrameFields:
    model_config = ConfigDict(extra='forbid')

    type: Literal['event']
    stream_id: str = Field(min_length=1, max_length=128, pattern='^[A-Za-z0-9_.-]+$')
    seq: int = Field(ge=1)
    client_send_mono_ns: int = Field(ge=0)
    event: StreamEvent


class StreamResultFrameFields:
    model_config = ConfigDict(extra='forbid')

    type: Literal['result']
    stream_id: str = Field(min_length=1, max_length=128, pattern='^[A-Za-z0-9_.-]+$')
    seq: int = Field(ge=1)
    client_send_mono_ns: int = Field(ge=0)
    attempt_id: str = Field(pattern='^[0-9a-f]{32}$')
    result: StreamResult


class JobAckPayloadFields:
    model_config = ConfigDict(extra='forbid')

    delivery_id: str = Field(min_length=1)
    corr_id: str = Field(min_length=1)
    attempt_id: str = Field(pattern='^[0-9a-f]{32}$')
    client_recv_mono_ns: int = Field(ge=0)


class StreamJobAckFrameFields:
    model_config = ConfigDict(extra='forbid')

    type: Literal['job_ack']
    stream_id: str = Field(min_length=1, max_length=128, pattern='^[A-Za-z0-9_.-]+$')
    seq: int = Field(ge=1)
    client_send_mono_ns: int = Field(ge=0)
    job_ack: JobAckPayload


class StreamAckFields:
    model_config = ConfigDict(extra='forbid')
    _wire_non_null_optional: ClassVar[frozenset[str]] = frozenset(('duplicate', 'error'))

    @model_validator(mode="before")
    @classmethod
    def _wire_optional_fields_are_absent_not_null(cls, value: Any) -> Any:
        if isinstance(value, dict):
            nulls = sorted(key for key in cls._wire_non_null_optional if value.get(key, _MISSING) is None)
            if nulls:
                raise ValueError(f"optional wire fields must be omitted, not null: {nulls}")
        return value

    type: Literal['ack']
    stream_id: str = Field(min_length=1, max_length=128, pattern='^[A-Za-z0-9_.-]+$')
    seq: int = Field(ge=1)
    status: int = Field(ge=100, le=599)
    server_recv_unix_ns: int = Field(ge=0)
    server_send_unix_ns: int = Field(ge=0)
    duplicate: bool | None = None
    error: str | None = None


class JobTimelineFields:
    model_config = ConfigDict(extra='forbid')

    enqueue_min_unix_ns: int = Field(ge=0)
    enqueue_max_unix_ns: int = Field(ge=0)
    claim_min_unix_ns: int = Field(ge=0)
    claim_max_unix_ns: int = Field(ge=0)
    socket_write_min_unix_ns: int = Field(ge=0)


class StreamJobFields:
    model_config = ConfigDict(extra='forbid')

    type: Literal['job']
    delivery_id: str = Field(min_length=1)
    attempt_id: str = Field(pattern='^[0-9a-f]{32}$')
    stream_id: str = Field(min_length=1, max_length=128, pattern='^[A-Za-z0-9_.-]+$')
    seq: int = Field(ge=1)
    replayed: bool
    timeline: JobTimeline
    job: PodJob


__all__ = ['JobAckPayloadFields', 'JobTimelineFields', 'StreamAckFields', 'StreamEventFields', 'StreamEventFrameFields', 'StreamJobAckFrameFields', 'StreamJobFields', 'StreamResultFields', 'StreamResultFrameFields', 'WIRE_BUNDLE_FORMAT', 'WIRE_BUNDLE_SHA256', 'WIRE_CONTRACT_VERSION']
